version: '3.2'

services:
  build-test:
    image: maven:3.6.3-jdk-11-slim
    command: |
      mvn -T 1.5C clean package -DfailIfNoTests=true -Dproject.version=${VERSION:-1.0-SNAPSHOT}
    working_dir: /app
    environment:
      AWS_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    volumes:
      - .:/app/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/:ro

  deploy-snapshot:
    image: maven:3.6.3-jdk-11-slim
    command: |
      mvn deploy -DskipTests=true
    working_dir: /app
    environment:
      AWS_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    volumes:
      - .:/app/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/:ro

  deploy-release:
    image: maven:3.6.3-jdk-11
    command: mvn -B -e gitflow:release -DreleaseVersion=$CIRCLE_TAG -DpostReleaseGoals='deploy -DskipTests'
    working_dir: /app
    environment:
      AWS_PROFILE: dev/vault
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    volumes:
      - .:/app/
      - ~/.m2/:/root/.m2/
      - ~/.aws/:/root/.aws/:ro
      - ~/.ssh/:/root/.ssh/:ro
